services:
  frontend:
    build: 
      context: ./dash_frontend
      dockerfile: Dockerfile
    container_name: olympia_frontend
    ports:
      - "3000:3000"
    environment:
      # IMPORTANT: This URL is used by the browser (client-side), not the container
      # Use 'localhost' when accessing from the same machine
      # Use your machine's IP (e.g., 192.168.1.x) when accessing from other devices on the network
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:5001
      - NODE_ENV=production
    networks:
      - olympia_network
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: olympia_backend
    ports:
      - "5001:5001"
    env_file:
      - ./api/.env
    environment:
      - FLASK_DEBUG=False
      - FLASK_PORT=5001
      # CRITICAL: Must bind to 0.0.0.0 to accept connections from outside the container
      - FLASK_HOST=0.0.0.0
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    networks:
      - olympia_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/widgets", "-X", "POST", "-H", "Content-Type: application/json", "-d", "{\"table\":\"test\"}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  olympia_network:
    driver: bridge
    name: olympia_network
