services:
  frontend:
    build: 
      context: ./dash_frontend
      dockerfile: Dockerfile
      args:
        # Pass the API URL as a build argument so it's available during Next.js build
        NEXT_PUBLIC_API_BASE_URL: http://backend:5001
    container_name: olympia_frontend
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      # Backend URL for server-side API calls (Next.js rewrites)
      # Uses Docker internal network name 'backend' to reach the API container
      - NEXT_PUBLIC_API_BASE_URL=http://backend:5001
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: olympia_backend
    ports:
      - "0.0.0.0:5001:5001"
    env_file:
      - ./api/.env
    environment:
      - FLASK_DEBUG=False
      - FLASK_PORT=5001
      # CRITICAL: Must bind to 0.0.0.0 to accept connections from outside the container
      - FLASK_HOST=0.0.0.0
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
