services:
  frontend:
    build: 
      context: ./dash_frontend
      dockerfile: Dockerfile
    container_name: olympia_frontend
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      # IMPORTANT: This URL is used by the browser (client-side), not the container
      # Must use the server's IP address so devices on the network can reach the API
      # Replace 172.19.1.95 with your server's actual IP if different
      - NEXT_PUBLIC_API_BASE_URL=http://172.19.1.95:5001
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: olympia_backend
    ports:
      - "0.0.0.0:5001:5001"
    env_file:
      - ./api/.env
    environment:
      - FLASK_DEBUG=False
      - FLASK_PORT=5001
      # CRITICAL: Must bind to 0.0.0.0 to accept connections from outside the container
      - FLASK_HOST=0.0.0.0
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
